version: 2
jobs:
    build:
        working_directory: ~/marcostagnicom
        docker:
            - image: circleci/node:8.12.0
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install marcostagni
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test
            - run:
                name: code-coverage
                command: 'npm run test:coverage'
            - run:
                name: build
                command: 'npm run build'
            - store_artifacts:
                path: coverage
                prefix: coverage

    publish_release:
        docker:
            - image: circleci/golang:1.8
        steps:
            - attach_workspace:
                at: ./
            - run:
                name: "Publish Release on GitHub"
                command: |
                    go get github.com/tcnksm/ghr
                    ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_BUILD_NUM} build-${CIRCLE_BUILD_NUM} ./

    deploy:
        machine:
            enabled: true
        steps:
            - run:
                name: Deploy Over SSH
                command: 'echo deploy'

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - publish_release:
                requires:
                    - build
            - deploy:
                requires:
                    - publish_release
                filters:
                    branches:
                        only: master
