version: 2
jobs:
    build:
        working_directory: ~/marcostagnicom
        docker:
            - image: circleci/node:8.12.0
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install marcostagni
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test
            - run:
                name: code-coverage
                command: 'npm run test:coverage'
            - run:
                name: build
                command: 'npm run build'
            - run:
                name: remove dev dependencies
                command: 'npm prune --production'
            - run:
                name: push new version
                command: echo ${CIRCLE_BUILD_NUM}
            - store_artifacts:
                path: test-results.xml
                prefix: tests
            - store_artifacts:
                path: coverage
                prefix: coverage
            - store_test_results:
                path: test-results.xml


    deploy:
        machine:
            enabled: true
        steps:
            - run:
                name: Deploy Over SSH
                command: 'echo deploy'

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - deploy:
                requires:
                    - build
                filters:
                    branches:
                        only: master
