version: 2
jobs:
    build:
        working_directory: ~/marcostagnicom
        docker:
            - image: circleci/node:8.12.0
        steps:
            - checkout
            - run:
                name: update-npm
                command: 'sudo npm install -g npm@5'
            - restore_cache:
                key: dependency-cache-{{ checksum "package.json" }}
            - run:
                name: install marcostagni
                command: npm install
            - save_cache:
                key: dependency-cache-{{ checksum "package.json" }}
                paths:
                    - ./node_modules
            - run:
                name: test
                command: npm test
            - run:
                name: code-coverage
                command: 'npm run test:coverage'
            - run:
                name: build
                command: 'npm run build'
            - run:
                name: remove dev dependencies
                command: npm prune --production
            - run:
                name: "Zip"
                command: |
                    mkdir build
                    zip -r build/app.zip ./
            - persist_to_workspace:
                  root: build
                  # Must be relative path from root
                  paths:
                      - app.zip
            - store_artifacts:
                path: coverage
                prefix: coverage

    publish_release:
        docker:
            - image: circleci/golang:1.12
        steps:
            - attach_workspace:
                  at: build
            - run:
                  name: what is inside this folder
                  command: ls -larch build/
#            - run:
#                name: "Publish Release on GitHub"
#                command: |
#                    go get github.com/tcnksm/ghr
#                    ghr -t ${GITHUB_TOKEN} v${CIRCLE_BUILD_NUM} build/

    deploy:
        machine:
            enabled: true
        steps:
            - run:
                name: Deploy Over SSH
                command: 'echo deploy'

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build
            - publish_release:
                  requires:
                      - build
            - deploy:
                  requires:
                      - publish_release
                  filters:
                      branches:
                          only: master